controllers_api:
    resource:
        path: ../src/Api/Controller/
        namespace: Api\Controller
    type: attribute
    prefix: '/api'

controllers_web:
    resource:
        path: ../src/Web/Controller/
        namespace: Web\Controller
    type: attribute
