name: CI Code Coverage

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          php_extensions: xdebug
          configuration: phpunit.xml.dist
          args: --coverage-text
          php_version: "8.2"
          vendored_phpunit_path: bin/phpunit
        env:
          XDEBUG_MODE: coverage
          TEST_NAME: Orchestra
